### PR TITLE
Allow opt-out of adding stdout/stderr env variables

### LINKED ISSUE #285: error: fork/exec /bin/sh: argument list too long
### What happened?

Running `pulumi up` on an existing stack on Linux fails.

Poking at the code, I see this is because of PULUMI_COMMAND_STDOUT/PULUMI_COMMAND_STDERR and the previous run containing rather long output.

https://github.com/pulumi/pulumi-command/blob/7c5c4bd68e66950c042c5ce1ad3eb6f9bfda835c/provider/pkg/provider/local/commandOutputs.go#L73-L78

Since I don't use this feature and I don't always have the option of adjusting limits, I'd like an option to turn it off. Furthermore, I'd prefer if the option could be made off by default as well, as I don't generally need this information in state files.

### Example

strace
```
sudo -E strace -E PATH=$PATH -u $USER -f -e trace=execve -s 1000 -v --signals=SIGPWR pulumi up 2> log
```

From log above, we can tell our command is not particularly long, the environment is massive.
```
execve("/bin/sh", ["/bin/sh", "-c", "ansible REDACTED"], ["SHELL=/bin/bash", ...REDACTED..., "PULUMI_COMMAND_STDOUT=ansible-playbook [core 2.14.6]\n  config file REDACTED"...]) = -1 E2BIG (Argument list too long)
```

### Output of `pulumi about`

```
CLI
Version      3.75.0
Go Version   go1.20.5
Go Compiler  gc

Host
OS       ubuntu
Version  20.04
Arch     x86_64

Backend
Name           REDACTED
URL            file://~
User           REDACTED
Organizations
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by julsemaan**
fixes #285

### CODE REVIEW

**Comment by julsemaan** [comment]
Not sure if I should be regenerating the SDKs and codegen, I wasn't able to get all SDKs to build on my box so hopefully this is something that can be done outside of this PR 🙏

**Comment by julsemaan** [comment]
Can I have one of the maintainers to run acceptance tests to move it forward 🙏 

Thanks!

**Comment by julsemaan** [comment]
@mikhailshilkov, thanks for getting these to run. Based on the output, it seems like I should be regenerating the SDKs myself within the PR? Is there a mechanism for doing this via GHA instead of relying on my dev machine to do this for all supported languages?

Thanks 🙏

**Comment by mikhailshilkov** [comment]
@julsemaan Yes, you will need to include SDK changes in the PR manually, there is no way to do that automatically at the moment. `make build_sdks` should do that. Let me know if you want help.

**Comment by iwahbe** [comment]
Hey @julsemaan. Thanks for opening this PR. I'm sorry it took so long to get to merging it.

The PR looks good to me. I'd like to see a quick test (not a full integration test) before we merge. Let me know if you want to write that or if you want me to take over here. Likewise on SDK generation.

Thanks for your contribution.

**Comment by julsemaan** [comment]
Hey folks, thanks for the feedback.

I'll certainly try to give it a shot to make this complete (at least the test, I had trouble with build_sdks for some languages)

**Comment by julsemaan** [comment]
I gave a shot to doing `build_sdks` but I'm still stuck on the Java SDK :/ 

@iwahbe, I think I'll take your offer of generating the SDKs for this PR

The test has been added in [c1b60ad](https://github.com/pulumi/pulumi-command/pull/355/commits/c1b60ad0bf6271541243e1e1768b8197bcfa6a2a)

Thanks!

**Review by iwahbe — APPROVED** [review]
@julsemaan Thanks for your contribution! LGTM

**Pull request merged**
