### PR TITLE
Use default implementation for input-output dependencies

### PR DESCRIPTION
**Pull request by iwahbe**
WireDependencies has quite a but of subtlety at this point. It needs to account for flowing computedness and secretness between inputs and outputs, each of which can be handled either together or separately. When this provider was implemented, the default implementation didn't work as expected, and didn't cover cases such as pass through inputs.

The pulumi-go-provider now does a much better job by default, so we can rely on that implementation. We expect the following semantics:
- If any input is computed, then all outputs are computed.
  - This does not apply to an output `k` if: - There is an input also called `k` and `k` is not computed. - `input[k] == output[k]`.
- If any input is secret, then the matching output of the same name is also secret.

This should fix (not closing) https://github.com/pulumi/pulumi-command/issues/256.
I'll close https://github.com/pulumi/pulumi-command/issues/256 once I merge the examples revert.

### CODE REVIEW

**Comment by t0yv0** [comment]
So removing custom configuration to rely on the defaults is looking good! 

I hear this is going to fix https://github.com/pulumi/pulumi-command/pull/274

I would love to see a test added that ensures 274 does not regress.

**Comment by Frassle** [comment]
> If any input is secret, then the matching output of the same name is also secret.

N.B. The engine does this for you anyway.

**Comment by iwahbe** [comment]
> > If any input is secret, then the matching output of the same name is also secret.
> 
> N.B. The engine does this for you anyway.

I thought that the engine only did that if the provider sent `AcceptSecrets: false`. @Frassle Does the engine gate any behavior (besides sending secrets) on `AcceptSecrets: true`?

**Review by t0yv0 — APPROVED** [review]
🚢

**Comment by t0yv0** [comment]
> If any input is secret, then the matching output of the same name is also secret.

Privately I think it's a misfeature that caters to Terraform design where every input has a matching output; both in the engine and any provider SDKs we built. I'd prefer dynamic tracing of secrets through black box transforms like TF providers, but for our own providers like command/docker make no black boxes but instead fully accurate secret tracing via Output and Apply.  

But that's a conversation for another day; whatever we have needs to be documented, and whatever we want to have instead needs to undergo change management from status quo which is difficult.

**Comment by t0yv0** [comment]
I'll file the dynamic secrets idea.

**Comment by Frassle** [comment]
> I thought that the engine only did that if the provider sent

No it always does it, it's supposed to help catch providers that didn't correctly flow secrets. Does mean a provider can't unsecret an output "x" if the input "x" is secret.

> Does the engine gate any behavior (besides sending secrets) on AcceptSecrets: true?

No, I think AcceptSecrets just changes if secret objects get sent on the wire protocol.

**Comment by Frassle** [comment]
> I'd prefer dynamic tracing of secrets through black box transforms like TF providers (though Ian notes it has security downsides), but for our own providers like command/docker make no black boxes but instead fully accurate secret tracing via Output and Apply.

Yes I agree, but pragmatism was that we do this in the engine for now.

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi/issues/14020 dynamic secrets idea, obviously not actionable for now but to reference in discussion like this.

**Pull request merged**
