### PR TITLE
Update pulumi/pulumi to v3.91.1

### PR DESCRIPTION
**Pull request by mjeffryes**
Doesn't look like there's actually any impact on the python SDK for command, but may as well bump it so we can easily verify it's ok.

### CODE REVIEW

**Comment by iwahbe** [comment]
There is. See https://github.com/pulumi/pulumi-command/pull/296.

**Comment by mjeffryes** [comment]
hmm... strange why I did not get the same changes in code gen as you did in #296. Will close in favor of your PR though

**Comment by iwahbe** [comment]
@mjeffryes Did you change .pulumi.version?

**Comment by mjeffryes** [comment]
ah, no I didn't. It's getting a little tricky to keep track of which repos have adopted that convention.

**Pull request closed without merging**
