### PR TITLE
Allow usage of bastion host for remotecommand and remotefilecopy

### LINKED ISSUE #131: Allow usage of bastion host for remote.NewCommand
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently it is not possible to execute a `remote.NewCommand` using a bastion host. This could be very useful for more advanced scenarios, where one would like to use Pulumi to replace `ansible`.

### Affected area/feature

The `remote.NewCommand` resource. I will submit a PR shortly with a potential implementation.

### PR DESCRIPTION
**Pull request by nicklasfrahm**
Closes #131.

### CODE REVIEW

**Comment by nicklasfrahm** [comment]
I would need some guidance on how I can test this, because I am not super familiar with the pulumi execution model.

**Comment by nicklasfrahm** [comment]
@jkisk, could you give the acceptance tests another shot?

**Comment by nicklasfrahm** [comment]
@danielrbradley Could you have a look at this? I am not quite sure why the test fail. For some reason the CI seems to have been canceled?

**Comment by dixler** [comment]
@nicklasfrahm FYI I'm in the process of rewriting the command provider using
https://github.com/pulumi/pulumi-go-provider

The draft is here https://github.com/pulumi/pulumi-command/pull/156 as I'm still adding comments.

The codebase should be more straightforward after it's merged. If it's more confusing, definitely let me know where I can add more comments to clarify. We want to make it more straightforward to write custom providers.

**Comment by adrianriobo** [comment]
@nicklasfrahm are you planning on rework this PR based on the new provider structure? This feature really help me out!. Otherwise I could rework it

**Comment by nicklasfrahm** [comment]
Currently not the plan, I opted to go a completely different route for my personal infrastructure automation. In our company we use `pulumi` but we don't have this as a use case at the moment.

**Comment by adrianriobo** [comment]
hey @nicklasfrahm  thx for quick response so I will try to adapt some of your work. Hopefully this feature can be added so if in future you got another use case for it you cam use it :+1:

**Comment by eBeyond** [comment]
I've got a usecase which needs the bastion-hosts feature... Is there any plan to merge this PR asap?

**Comment by iwahbe** [comment]
Hey @nicklasfrahm. This feature has been merged as part of https://github.com/pulumi/pulumi-command/pull/269, very much because of your PR. Thanks for contributing!

**Pull request closed without merging**
